### ISSUE TITLE
Variable name correct?

### ISSUE THREAD

**Issue by raandree** [AutomatedLab/AutomatedLab.Common#15]
Is the variable name $requestParameters correct here?

https://github.com/AutomatedLab/AutomatedLab.Common/blob/962e0aa7f3e5d1080cec080e064f10f241ab700c/AutomatedLab.Common/TeamFoundation/Public/Projects/Get-TfsProcessTemplate.ps1#L53

**Comment by nyanhp** [comment]
No, of course not. Good catch.
