### ISSUE TITLE
New-CATemplate

### ISSUE THREAD

**Issue by bencoremans** [AutomatedLab/AutomatedLab.Common#27]
I had an issue with duplicating a template. The solution was to set the parameter EnrollmentFlags to 0.

The suggested values of the parameter EnrollmentFlags are _"IncludeSymmetricAlgorithms, CAManagerApproval, KraPublish, DsPublish, AutoenrollmentCheckDsCert, Autoenrollment, ReenrollExistingCert, RequireUserInter
action, RemoveInvalidFromStore, AllowEnrollOnBehalfOf, IncludeOcspRevNoCheck, ReuseKeyTokenFull, BasicConstraintsInEndEntityCerts, IgnoreEnrollOnReenro
llment, IssuancePoliciesFromRequest"_ but does not include "None".

When the parameter is not set, the command fails.
So maybe for future releases, I suggest to set the EnrollmentFlags to 0 by default.

New-CATemplate -SourceTemplateName "EnrollmentAgentOffline" -TemplateName "BCOEnrollmentAgentOffline2" -DisplayName "BCO Exchange Enrollment Agent (Offline Request)2" -Version 2 -ApplicationPolicy ENROLLMENT_AGENT -PrivateKeyFlags None -EnrollmentFlags 0

I appreciate your module very much btw!

**Comment by raandree** [comment]
Thanks for having reported this to us!
