### ISSUE TITLE
Can you support PSRemoting as well as remote registry access in Get-DotNetFrameworkVersion.ps1?

### ISSUE THREAD

**Issue by EliteLoser** [AutomatedLab/AutomatedLab.Common#47]
If not, I do it myself here: https://github.com/EliteLoser/DotNetVersionLister ...

**Comment by EliteLoser** [comment]
I don't distinguish between the different Windows 10 versions, etc., but I guess I could spend 20 minutes on it..

**Comment by raandree** [comment]
We use the common helper functions in this module for [AutomatedLab](https://github.com/AutomatedLab/AutomatedLab), so the functionality is pretty targeted. In an AL deployment we channel everything through PSRemoting.

**Comment by EliteLoser** [comment]
I see. Feel free to close this issue, then..
