### ISSUE TITLE
Get-DotNetFrameworkVersion.ps1 script returns incorrect result for build 528040

### ISSUE THREAD

**Issue by andrewmolyneux** [AutomatedLab/AutomatedLab.Common#95]
I believe build 528040 corresponds to .NET Framework 4.8, not 4.7.2 as indicated by this script.
See [my comment on this commit](https://github.com/AutomatedLab/AutomatedLab.Common/commit/82326d4b7e29c6c7c42d424114591c3339adf5c2#commitcomment-40788989).

**Comment by raandree** [comment]
Already fixed in #96.
